# Jekyll settings
permalink: /:categories/:year/:month/:title/
pygments: true
markdown: rdiscount

exclude: ["README.md", "LICENSE.md", "Gemfile", "Gemfile.lock"]

# Site settings
url: http://www.radley.se
title: Leon Radley
author: Leon Radley
simple_search: http://google.com/search